// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaaGZbS_cPp8N0PtGDmRogIDMprT6Aqes',
    appId: '1:938475397395:web:918671f46a3b1438583ae6',
    messagingSenderId: '938475397395',
    projectId: 'saaya-your-silent-protector',
    authDomain: 'saaya-your-silent-protector.firebaseapp.com',
    storageBucket: 'saaya-your-silent-protector.firebasestorage.app',
    measurementId: 'G-MJK1JWETM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH0DZ2GvgUhrltmmTr_z83wR9c2HTOeY4',
    appId: '1:938475397395:android:af8a9dec150729af583ae6',
    messagingSenderId: '938475397395',
    projectId: 'saaya-your-silent-protector',
    storageBucket: 'saaya-your-silent-protector.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa3TNxT8NbL6OsWsZBuw3sZ6TQH0MhrIs',
    appId: '1:938475397395:ios:59ce6b8bca8a6225583ae6',
    messagingSenderId: '938475397395',
    projectId: 'saaya-your-silent-protector',
    storageBucket: 'saaya-your-silent-protector.firebasestorage.app',
    androidClientId: '938475397395-evl4588gif2jcn21jkdcpfanvhisca4t.apps.googleusercontent.com',
    iosClientId: '938475397395-23ajm2n4fd3p2ad2ps9csehi383o5vhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.technova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa3TNxT8NbL6OsWsZBuw3sZ6TQH0MhrIs',
    appId: '1:938475397395:ios:59ce6b8bca8a6225583ae6',
    messagingSenderId: '938475397395',
    projectId: 'saaya-your-silent-protector',
    storageBucket: 'saaya-your-silent-protector.firebasestorage.app',
    androidClientId: '938475397395-evl4588gif2jcn21jkdcpfanvhisca4t.apps.googleusercontent.com',
    iosClientId: '938475397395-23ajm2n4fd3p2ad2ps9csehi383o5vhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.technova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaaGZbS_cPp8N0PtGDmRogIDMprT6Aqes',
    appId: '1:938475397395:web:63af0643e67342c5583ae6',
    messagingSenderId: '938475397395',
    projectId: 'saaya-your-silent-protector',
    authDomain: 'saaya-your-silent-protector.firebaseapp.com',
    storageBucket: 'saaya-your-silent-protector.firebasestorage.app',
    measurementId: 'G-J44CN5JHHB',
  );
}
